# Generated by Django 4.2.4 on 2023-08-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('birthday', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
                ('twitter', models.CharField(max_length=150)),
            ],
        ),
    ]
