# Generated by Django 4.2.4 on 2023-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('هوش مصنوعی', 'هوش مصنوعی'), ('توسعه وب', 'توسعه وب'), ('رابط کاربری', 'رابط کاربری')], max_length=40)),
                ('image', models.ImageField(upload_to='works')),
                ('title', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
