# Generated by Django 4.2.4 on 2023-08-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
