# Generated by Django 4.2.4 on 2023-08-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works_app', '0004_category_remove_work_subject_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='subject',
            field=models.CharField(default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works_app.category', verbose_name='دسته بندی'), max_length=50),
        ),
    ]
