# Generated by Django 4.2.4 on 2023-08-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works_app', '0005_work_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='subject',
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='works_app.category', verbose_name='دسته بندی'),
        ),
    ]
