# Generated by Django 4.2.4 on 2023-08-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works_app', '0006_remove_work_subject_alter_work_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('paragraph', models.TextField()),
                ('image1', models.ImageField(upload_to='Project')),
                ('image2', models.ImageField(upload_to='Project')),
                ('image3', models.ImageField(upload_to='Project')),
            ],
        ),
    ]
