# Generated by Django 4.2.4 on 2023-09-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works_app', '0007_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
