# Generated by Django 4.2.4 on 2023-09-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works_app', '0009_remove_work_category_delete_category_delete_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='works')),
                ('client', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='works')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='works')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='works')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='works_app.category', verbose_name='دسته بندی')),
            ],
        ),
    ]
